name: PluginManager
main: xyz.acrylicstyle.plugin.PluginManager
version: 0.0.2
softdepend:
  - TomeitoLib
commands:
  pman:
    description: "Plugin Manager"
    usage: "/<command>"
    permission: pluginmanager.root_command
    aliases: ["pm"]