name: PluginManager
main: xyz.acrylicstyle.plugin.PluginManager
version: 1.0.0
commands:
  pman:
    description: "Plugin Manager"
    usage: "/<command>"
    permission: pluginmanager.root_command
    aliases: ["pm"]